Plugin demos
Cr1t-GYM/Jenkinsfile-runner-actions-demo pull request #13
Opened 2022-08-17 20:16 UTC by Cr1t-GYM

- [x] Add detailed descriptions for s3-artifact-manager demo.
- [x] Add detailed descriptions for jobcacher demo.
- [x] Add detailed descriptions for remote agent demo.
- [x] Add related changes in the main README.

2022-08-21 07:09 UTC, krisstern requested changes
Overall the PR looks good, except some minor editing has been requested.

2022-08-21 07:09 UTC, krisstern commented on demo/jobcacher/README.md
> +If you use `AWS S3` like this example, you need to know your the region of the user, `AWS access key id`,
```suggestion
If you use `AWS S3` like this example, you will need to know your the region of the user, `AWS access key id`, 
```

2022-08-21 07:09 UTC, krisstern commented on demo/remote-agent/README.md
> +   If you create the machines in cloud providers such as AWS, you need to create the correct inbound rule for the port 4444.
```suggestion
   If you create the machines in cloud providers such as AWS, you will need to create the correct inbound rule for the port 4444.
```

2022-08-21 07:09 UTC, krisstern commented on demo/remote-agent/README.md
> +   For Example, if you use port 4444 for network redirection, you need to create the TCP protocol for port 4444 and allow the network from any ip ranges.
```suggestion
   For Example, if you use port 4444 for network redirection, you will need to create the TCP protocol for port 4444 and allow the network from any ip ranges.
```

2022-08-21 07:09 UTC, krisstern commented on demo/remote-agent/README.md
> +5. In your workflow definition, you need to set up your credentials and `jfr-container-action` correctly.
```suggestion
5. In your workflow definition, you will need to set up your credentials and `jfr-container-action` correctly.
```

2022-08-21 07:09 UTC, krisstern commented on demo/remote-agent/README.md
> +   If you create the machines in cloud providers such as AWS, you need to create the correct inbound rule for the port 4444.
```suggestion
   If you create the machines in the cloud using cloud providers such as AWS, you will need to create the correct inbound rule for the port 4444.
```

2022-08-21 07:09 UTC, krisstern commented on demo/s3-artifact-manager/README.md
> +you need to give it `AmazonS3FullAccess` in the IAM user permission page.
```suggestion
you will need to grant it `AmazonS3FullAccess` in the IAM user permission page.
```

2022-08-21 07:09 UTC, krisstern commented on demo/s3-artifact-manager/README.md
> +5. In your workflow definition, you need to set up your credentials and `jfr-container-action` correctly.
```suggestion
5. In your workflow definition, you will need to set up your credentials and `jfr-container-action` correctly.
```

2022-08-21 07:09 UTC, krisstern commented on demo/s3-artifact-manager/README.md
> +Here is the step-by-step example in `jfr-container-action`.
```suggestion
Here is the step-by-step example for `jfr-container-action`:
```

2022-08-22 14:44 UTC, krisstern approved these changes

2022-08-23 22:26 UTC, AbhyudayaSharma approved these changes

2022-08-23 23:28 UTC, merged